church_name: Calvary Bible Church
church_logo_image_path: 'http://sitesforchurch.s3.amazonaws.com/1-3.png'
church_logo2_image_path: 'http://sitesforchurch.s3.amazonaws.com/1-3.png'
church_description: 'How can we help you? Do you need prayer or need a friend? Calvary Bible Church strives to live out the calling to be more like Jesus Christ, by studying and obeying the principles He has set forth in His Word.'
phone: (410) 848-1848
church_email: calvarybiblechurchmaryland@yahoo.com
facebook: 'https://www.facebook.com/calvarybiblechurchmaryland'
twitter:
youtube:
address: 2447 Hampstead Mexico Rd.
address2:
City: Westminster
State: MD
Zip: '21157'
Service_Schedule:
  - service_name: Sunday School
    service_time: '9:30 AM'
  - service_name: Sunday Morning Service
    service_time: '10:45 AM'
  - service_name: Sunday Evening Service
    service_time: '6:00 PM'
  - service_name: Wednesday Bible Study and Prayer Meeting
    service_time: '7:00 PM'
  - service_name: Thursday Night Youth Group
    service_time: '7:00 PM'
lattitude: '39.608938'
longitude: '-76.9100337'
google_maps_embed_code: "<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3073.8110817643887!2d-76.91003368421761!3d39.60893797946713!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x54cad6bcf5e7f0dd!2sCalvary+Bible+Church!5e0!3m2!1sen!2sus!4v1474036857117\\\" width=\"100%\" height=\"400\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>"
map_zoom_level: 16
main_blog_image: /uploads/1.jpg
main_sermon_image: /uploads/2.jpg
default_calendar_image: /uploads/3.jpg
Google_calendar_id: CalvaryBibleMD@Gmail.com